---
config:
  theme: neutral
  layout: elk
---
erDiagram
	direction TB
	TAXPAYER_DIM {
		string TAXPAYER_KEY PK ""  
		string FILE_TYPE  ""  
		string IT_REF_NO  ""  
		string IT_ASSM_BRANCH  ""  
		string ACTIVE_FLAG  ""  
		string NEW_IC_NO  ""  
		string OLD_IC_NO  ""  
		string NAME  ""  
		string PASSPORT_NO  ""  
		string POLICE_NO  ""  
		string ARMY_NO  ""  
		string ROB_NO  ""  
		string ROC_NO  ""  
		string PHONE_NO  ""  
		string SEX  ""  
		string MARITAL_STATUS  ""  
		string MALAYSIAN_CITIZEN  ""  
		string CITIZEN_COUNTRY  ""  
		string EPF_NO  ""  
		string EMPLOYER_NO  ""  
		date REGISTRATION_DATE  ""  
		string FILE_STATUS  ""  
		string VIP_CODE  ""  
		string NO_OF_PARTNERSHIP  ""  
		string COORPORATION_TYPE  ""  
		string TRUST_TYPE  ""  
		string REGISTRATION_CERT_NO  ""  
		string WILL_INDICATOR  ""  
		string AUTHORISATION_LETTER_INDICATOR  ""  
		date AUTHORISATION_LETTER_DATE  ""  
		string LOCAL_DECEASED_INDICATOR  ""  
		string DECEASE_COUNTRY_CODE  ""  
		string RACE_CODE  ""  
		string RELIGION_CODE  ""  
		string PROFESSION_CORD  ""  
		string IMMIGRATION_INDICATOR  ""  
		string TOTAL_CHILDREN  ""  
		string PCB_TYPE  ""  
		string IT_COLLECTION_BRANCH  ""  
		string CKHT_ASSM_BRANCH  ""  
		string CKHT_COLLECTION_BRANCH  ""  
		date START_OF_ACCOUNT_PERIOD  ""  
		date END_OF_ACCOUNT_PERIOD  ""  
		string COMPANY_STATUS  ""  
		string EST_IND  ""  
		string HONORIFIC_CD  ""  
		string TITLE_NAME  ""  
		string TYP  ""  
		string RESIDENT_IND  ""  
		string RESIDENT_COUNTRY_CD  ""  
		string CLASS_CD  ""  
		string COMPANY_TYP  ""  
		string CREATION_REASON  ""  
		string PERMANENT_IND  ""  
		string NET_IT_LGR_DR_AMT  ""  
		string NET_IT_REFUND_CR_AMT  ""  
		string NET_CKHT_LGRBL_AMT  ""  
		string NET_IT_UPOS_CR_AMT  ""  
		string NET_IT_UPOS_DR_AMT  ""  
		string INVESTIGATION_IND  ""  
		string INVEST_ASMSTART_YR  ""  
		string INVEST_ASM_END_YR  ""  
		string CMULATVE_ASSET_AMT  ""  
		date LAST_CP77_CP38_DT  ""  
		string SECT_8_EXEMPT_IND  ""  
		string SECTION_104_IND  ""  
		string MARKED_AS_DUPL_IND  ""  
		string WRITE_OFF_STAT  ""  
		string WRITE_OFF_REASONCD  ""  
		string REMARKS  ""  
		date INACTIVE_DT  ""  
		date ACTIVATION_DT  ""  
		date BANKRUPT_DT  ""  
		string BANKRUPT_IND  ""  
		string E_MALAYSIA_ITREFNO  ""  
		string BANK_CD  ""  
		string BANK_ACCT_NO  ""  
		string NUM_OF_TIME_AUDIT  ""  
		string AUDIT_CYCLE  ""  
		date EFFECTIVE_DATE  ""  
		string SOURCE_SYSTEM_ID  ""  
		timestamp LOADING_TIMESTAMP  ""  
		string NR_START_YEAR  ""  
		string NR_END_YEAR  ""  
		string SOURCE_FLAG  ""  
		date BIRTH_DT  ""  
		date DEATH_DT  ""  
	}

	EXT_ADDR_DIM {
		string REC_ID PK ""  
		string TAXPAYER_KEY FK ""  
		string SOURCE_SYSTEM_ID  ""  
		date EFFECTIVE_DATE  ""  
		string PMAKLUMAT_ID  ""  
		string KATEGORI_ID  ""  
		string ADDRESS_TYPE  ""  
		string ADDRESS  ""  
		string CITY  ""  
		string STATE  ""  
		string POSTCODE  ""  
		string TELEPHONE_NO  ""  
		timestamp LOADING_TIMESTAMP  ""  
	}

	UNREG_TAXP_DIM {
		string TAXPAYER_KEY PK ""  
		string NEW_IC_NO  ""  
		string OLD_IC_NO  ""  
		string ROB_NO  ""  
		string ROC_NO  ""  
		string NAME  ""  
		string PHONE_NO  ""  
		string REG_STATUS  ""  
		string ACTIVE_FLAG  ""  
		date EFFECTIVE_DATE  ""  
		string SOURCE_SYSTEM_ID  ""  
		timestamp LOADING_TIMESTAMP  ""  
		string PASSPORT_NO  ""  
		string POLICE_NO  ""  
		string ARMY_NO  ""  
	}

	SSM_OWNERSHIP_INFO_FACT {
		string OTHER_TI_KEY PK ""  
		string TAXPAYER_KEY FK ""  
		string OLDICNUMBER  ""  
		string NEWICNUMBER  ""  
		date STARTDT  ""  
		date RESIGNDT  ""  
		string CHECKDIGIT  ""  
		string BUSINESS_NAME  ""  
		string OWNERNAME  ""  
		string CARDTYPE  ""  
		date BIRTHDATE  ""  
		string GENDER  ""  
		string RACE  ""  
		string OTHRACE  ""  
		string NATIONALITY  ""  
		string STATUS  ""  
		string AMENDMENTTYPE  ""  
		string DESIGNATION  ""  
		date EFFECTIVE_DATE  ""  
		string SOURCE_SYSTEM_ID  ""  
		timestamp LOADING_TIMESTAMP  ""  
	}

	SSM_COMP_INFO_FACT {
		string OTHER_TI_KEY PK ""  
		date EFFECTIVE_DATE  ""  
		string TAXPAYER_KEY FK ""  
		string COMPANYSTATUS  ""  
		date INCORPORATIONDATE  ""  
		string COMPANYOLDNAME  ""  
		date COMPNAMECHANGEDATE  ""  
		string WINDINGUPTYPE  ""  
		string COMPANYTYPE  ""  
		string COMPANY_CATEGORY  ""  
		date ROBSTARTDT  ""  
		date ROBEXPIRYDT  ""  
		date ROBTERMINATEDT  ""  
		date ROBAMENDMENTDT  ""  
		string BUSINESS_DESC  ""  
		string ROBOWNERCOUNT  ""  
		string SOURCE_SYSTEM_ID  ""  
		timestamp LOADING_TIMESTAMP  ""  
		string FILE_TYPE  ""  
		string IT_REF_NO  ""  
	}

	SSM_SHAREHOLDER_FACT {
		string OTHER_TI_KEY PK ""  
		string IDTYPE  ""  
		string ID  ""  
		string TAXPAYER_KEY FK ""  
		string NAME  ""  
		date BIRTHDATE  ""  
		string SHARE  ""  
		date EFFECTIVE_DATE  ""  
		string SOURCE_SYSTEM_ID  ""  
		timestamp LOADING_TIMESTAMP  ""  
	}

	SSM_CO_OFFICER_FACT {
		string OTHER_TI_KEY PK ""  
		string ID_TYPE  ""  
		string IC_PASSPORT_NO  ""  
		string DESIGNATION  ""  
		date STARTDT  ""  
		date ENDDT  ""  
		string TAXPAYER_KEY FK ""  
		string OFFICER_NAME  ""  
		date OFFICER_BDATE  ""  
		string ADDR  ""  
		string POSTCODE  ""  
		string TOWN  ""  
		string STATE  ""  
		date EFFECTIVE_DATE  ""  
		string SOURCE_SYSTEM_ID  ""  
		timestamp LOADING_TIMESTAMP  ""  
	}

	SSM_BALANCE_SHEET_FACT {
		string OTHER_TI_KEY PK ""  
		date FINANCIALYEARENDDATE  ""  
		string TAXPAYER_KEY FK ""  
		string AUDITFIRMNO  ""  
		string AUDITFIRMNAME  ""  
		string AUDITFIRMADDR1  ""  
		string AUDITFIRMADDR2  ""  
		string AUDITFIRMADDR3  ""  
		string AUDITFIRMPOSTCODE  ""  
		string AUDITFIRMTOWN  ""  
		string AUDITFIRMSTATE  ""  
		date DATEOFTABLING  ""  
		string ACCOUNTTYPE  ""  
		string FINANCIALRPTTYPE  ""  
		string NON_CURRENT_ASSETS  ""  
		string TOTAL_INVESTMENT  ""  
		string CURRENT_ASSETS  ""  
		string OTHER_ASSET  ""  
		string CONTIGENT_LIABILITY  ""  
		string SHARE_CAPITAL  ""  
		string SHAREPREMIUM  ""  
		string UNAPPROPRIATEPROFIT  ""  
		string MINORITYINTEREST  ""  
		string SHAREAPPACCT  ""  
		string LONGTIMEDEFLIAB  ""  
		string CURRENTLIAB  ""  
		date EFFECTIVE_DATE  ""  
		string SOURCE_SYSTEM_ID  ""  
		timestamp LOADING_TIMESTAMP  ""  
	}

	SSM_SHARE_CAPITAL_FACT {
		string OTHER_TI_KEY PK ""  
		string TAXPAYER_KEY FK ""  
		string AUTHORISEDCAPITAL  ""  
		string NO_OF_SHARES  ""  
		string NOMINAL_VALIE  ""  
		string NUMBER_OF_SHARE  ""  
		string NOMINAL_VALUE  ""  
		string OTH_NUMBER_OF_SHARES  ""  
		string OTH_NOMINAL_VALUE  ""  
		string ORD_ISSUED_CASH  ""  
		string ORD_ISSUED_NONCASH  ""  
		string ORD_ISSUED_NOMINAL  ""  
		string ISSUED_CASH  ""  
		string ISSUED_NONCASH  ""  
		string ISSUED_NOMINAL  ""  
		string OTH_ISSUED_CASH  ""  
		string OTH_ISSUED_NONCASH  ""  
		string OTH_ISSUED_NOMINAL  ""  
		date EFFECTIVE_DATE  ""  
		string SOURCE_SYSTEM_ID  ""  
		timestamp LOADING_TIMESTAMP  ""  
	}

	SSM_PROFIT_LOSS_FACT {
		string OTHER_TI_KEY PK ""  
		date FINYRENDDT  ""  
		string TAXPAYER_KEY FK ""  
		string ACCOUNT_TYPE  ""  
		string FINANCIALRPTTYPE  ""  
		string TURNOVER  ""  
		string REVENUE  ""  
		string PRLOSSBFTAX  ""  
		string PRLOSSAFTAX  ""  
		string EXTRAORDITEM  ""  
		string MINORITYINTEREST  ""  
		string SHAREHOLDER_PROFIT  ""  
		string PRIOR_ADJUSTMENT  ""  
		string NET_DIVIDEND  ""  
		string TRANSFERRED  ""  
		string OTHERS  ""  
		string INAPPRPROFITCF  ""  
		string GROSSDIVRATE  ""  
		string INAPPRPROFITBF  ""  
		date EFFECTIVE_DATE  ""  
		string SOURCE_SYSTEM_ID  ""  
		timestamp LOADING_TIMESTAMP  ""  
	}

	SSM_DIM {
		string OTHER_TI_KEY PK ""  
		string ROB  ""  
		string ROC  ""  
		string TYPE  ""  
		string BUSINESS_COMPANY_NAME  ""  
		date EFFECTIVE_DATE  ""  
		string SOURCE_SYSTEM_ID  ""  
		timestamp LOADING_TIMESTAMP  ""  
	}

	Untitled-Entity {

	}

	Untitled-Entity-1 {

	}

	TAXPAYER_DIM||--o{EXT_ADDR_DIM:"TAXPAYER_KEY"
	TAXPAYER_DIM||--o|UNREG_TAXP_DIM:"TAXPAYER_KEY"
	TAXPAYER_DIM||--o{SSM_OWNERSHIP_INFO_FACT:"TAXPAYER_KEY"
	TAXPAYER_DIM||--o{SSM_COMP_INFO_FACT:"TAXPAYER_KEY"
	TAXPAYER_DIM||--o{SSM_SHAREHOLDER_FACT:"TAXPAYER_KEY"
	TAXPAYER_DIM||--o{SSM_CO_OFFICER_FACT:"TAXPAYER_KEY"
	TAXPAYER_DIM||--o{SSM_BALANCE_SHEET_FACT:"TAXPAYER_KEY"
	TAXPAYER_DIM||--o{SSM_SHARE_CAPITAL_FACT:"TAXPAYER_KEY"
	TAXPAYER_DIM||--o{SSM_PROFIT_LOSS_FACT:"TAXPAYER_KEY"
	SSM_DIM||--o{SSM_OWNERSHIP_INFO_FACT:"OTHER_TI_KEY"
	SSM_DIM||--o{SSM_COMP_INFO_FACT:"OTHER_TI_KEY"
	SSM_DIM||--o{SSM_SHAREHOLDER_FACT:"OTHER_TI_KEY"
	SSM_DIM||--o{SSM_CO_OFFICER_FACT:"OTHER_TI_KEY"
	SSM_DIM||--o{SSM_BALANCE_SHEET_FACT:"OTHER_TI_KEY"
	SSM_DIM||--o{SSM_SHARE_CAPITAL_FACT:"OTHER_TI_KEY"
	SSM_DIM||--o{SSM_PROFIT_LOSS_FACT:"OTHER_TI_KEY"
	SSM_DIM}|--|{Untitled-Entity-1:"  "
